import type { Metadata } from "next";
import "./globals.css";
import NeueMontreal from "./fonts";
import Navbar from "@/components/navbar/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={NeueMontreal.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
